### ISSUE TITLE
Enable Sourcelink on Package

### ISSUE THREAD

**Issue by michael-hawker** [microsoftgraph/msgraph-sdk-dotnet-core#126] opened 2020-07-23 22:25 UTC
![image](https://user-images.githubusercontent.com/24302614/88344536-a5923680-ccf8-11ea-995f-ac39c3908af5.png)

### Expected behavior
Sourcelink would allow for easier debugging of the SDK code.

### Actual behavior
No sourcelink provided.

**Comment by ddyett** [comment] 2020-08-03 21:09
Closing this as duplicate of https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/133 .  We are tracking this for all packages.

**Comment by zengin** [comment] 2021-03-25 20:53
reopening to represent repo specific fix

**Closed** 2021-03-25 21:07 UTC
