### ISSUE TITLE
Deserialization issue when using both the Beta and non-beta libaries

### ISSUE THREAD

**Issue by ryannewington** [microsoftgraph/msgraph-sdk-dotnet-core#139] opened 2020-10-01 07:06 UTC
I've run into a unique issue in the scenario where one needs to use the beta and non-beta SDKs in one project. I've followed the guides around using the `extern alias` to set this up, and that all works fine.

However, there is an issue with the DerivedTypeConverter in the core graph API that prevents this from working as intended. 

The converter contains [a cache](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/dc8ae2e7cc49a8f2240d2cba707ef52044ecdfa6/src/Microsoft.Graph.Core/Serialization/DerivedTypeConverter.cs#L75) that maps the odata type name found in the deserialized response, to a .NET type.

When you deserialize an object (eg a Team), it will cache the `microsoft.graph.team` odata type name against the first .NET type that you deserialized with. If you then try to deserialize with the type from the other assembly, the cache returns the type that was first matched.

So if you first retrieved a non-beta `Microsoft.Graph.Teams` object, all subsequent calls to deserialize an odata `microsoft.graph.teams` object will use the non-beta object, even when that call was made using the beta library. 

In practice, this should always result in an InvalidCastException, but in a real-world implementation, I've seen the de-serialization actually 'succeed', resulting in an in-memory corruption of the Teams object. The in-memory representation of the internal fields was misaligned due to the beta and non-beta objects having different field offsets.

I've written a small sample project to reproduce this issue. In this case, an InvalidCastException is thrown when the second item it to be deserialized. 

[repro.zip](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/files/5309918/repro.zip)

While I get that combining the two libraries isn't ideal, but its explicitly called out that we shouldn't be using the beta API endpoint for production usage. That's not always possible, especially with things like the teams API still very much under development. Coexisting the two libraries is needed to be able to only call the beta endpoint when absolutely necessary. Not using the beta endpoint isn't an option because the functionality needed simply isn't available in the non-beta endpoint.
 
[AB#7181](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7181)

**Comment by zengin** [comment] 2020-10-16 06:20
I think that we need to define a new `BetaDerivedTypeConverter` with a separate type cache and assign the new converter as `JsonConverter` while generating for Beta.

I thought about incorporating two separate caches into the same converter or have the type cache key use the version information to prevent collision, but I don't think we have a version hint in that context to determine which cache to choose. What do you think @MIchaelMainer?

**Comment by andrueastman** [comment] 2020-10-16 07:37
@zengin I think that is a good idea. Maybe we probably make one converter a subclass of the other to prevent all that code from being duplicated.

**Comment by MIchaelMainer** [comment] 2020-10-16 08:00
The alternative is to create a beta namespace. Ideally, this would happen in AGS and they'd handle the conversion for the workloads. There is probably a lot of work to do that.

We could generate a beta namespace for the beta models. The problem is the odata.type will be in same namespace as v1.0 so we are back to the same issue of needing a hint.

So, the hint is the odata.context which provides the endpoint context. We can create/update the cache based on odata.context as key where the key is https://**graph.microsoft.com/v1.0/**$metadata#applications. I don't think we'll need a `BetaDerivedTypeConverter`, just a separate cache.

**Comment by zengin** [comment] 2020-10-16 08:32
If the response is guaranteed to have odata.context, we don't even need a separate cache. The cache key can prefix or postfix endpoint information to avoid collision.

**Comment by andrueastman** [comment] 2021-06-07 07:23
This is now closed via #256 and available through https://www.nuget.org/packages/Microsoft.Graph.Core/2.0.0-preview.12

**Closed by andrueastman** 2021-06-07 07:23 UTC
Labels: 2.0, Bug, promote
