### ISSUE TITLE
Transient 'InvalidAuthenticationToken' error with Managed identities.

### ISSUE THREAD

**Issue by spmanjunath** [microsoftgraph/msgraph-sdk-dotnet-core#222] opened 2021-03-16 07:20 UTC
I have an Azure function that uses Managed Identities to interact with Microsoft Graph API's using Graph SDK.  This function has been running successfully for past several months, automatically fetching the tokens and interacting with the API's.  However, yesterday there was unexplained authentication failures lasting for almost 2 hrs, after which the authentication worked as expected.   The failures are concerning because of the duration for which it occurred. 

Below are the first and the last error that occurred.
**First authentication error:**
```
Code: InvalidAuthenticationToken
Message: Signing key is invalid.
Inner error:
	AdditionalData:
	date: 2021-03-15T19:20:35
	request-id: c805eb4e-fa66-4797-8307-4f2d7c0e1ba9
	client-request-id: c805eb4e-fa66-4797-8307-4f2d7c0e1ba9
ClientRequestId: c805eb4e-fa66-4797-8307-4f2d7c0e1ba9
```
 **Last recorded authentication error:**
```
Code: InvalidAuthenticationToken
Message: Signing key is invalid.
Inner error:
	AdditionalData:
	date: 2021-03-15T21:12:32
	request-id: e0e2d114-a9e1-4f52-bc85-aaaa3b848843
	client-request-id: e0e2d114-a9e1-4f52-bc85-aaaa3b848843
ClientRequestId: e0e2d114-a9e1-4f52-bc85-aaaa3b848843
```

Below code is used to construct GraphServiceClient object.
 ```
public virtual GraphServiceClient GetClient()
  => new GraphServiceClient(new DelegateAuthenticationProvider(
      async requestMessage =>
      {
          string accessToken = await new Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider().GetAccessTokenAsync("00000003-0000-0000-c000-000000000000");
          requestMessage.Headers.Authorization = new AuthenticationHeaderValue("Bearer",
              accessToken);
      }));
```

I am interested to know what caused these errors, how to avoid it, and also how to isolate from such errors.  The inbuilt retry mechanism (handling transient failures) of Graph SDK will not be of help here because,
* I am not sure if 401 errors can be clubbed under transient failures - please correct if i am wrong.
* Considering the Serverless client (Azure function implementation) and length of time for which the failure occurred
* As per the 'conditions for retry' as it is implemented within Graph SDK (retry mechanism) 401 is not a candidate for transient failure.

Interested to know your opinion on the above.

Thanks.

**Comment by AlexandreArpin** [comment] 2021-03-16 14:25
There was a global outage of Azure AD Authentication which probably explains the issue you're seeing.

https://status.azure.com/en-us/status/history/

**Comment by andrueastman** [comment] 2021-03-19 07:56
@spmanjunath Thanks for opening this issue.

I believe this was caused by the outage as mentioned above and not caused by the SDK. Furthermore, you are correct as 401 errors are not classified as 'transient' errors. 

As the issue was caused by the service, the relevant team will be putting measures in place so that it doesn't occur again. I will close this issue for now since it was fixed. Please feel free to open a new issues in the event something else comes up.

**Closed by andrueastman** 2021-03-19 07:56 UTC
